### ISSUE TITLE
Contribution page redo

### ISSUE THREAD

**Issue by kasenvr** [kasenvr/athena-docs-sphinx#6]
The page name needs to be changed to something like Build from Source that's more indicative of what it is.

https://docs.projectathena.dev/contribute.html

The whole page needs updating + link correction, we do not have a CLA but we should probably note that all contributions *must* be licensed as Apache 2.0 or similar upon submission.

**Comment by ctrlaltdavid** [comment]
PR: https://github.com/kasenvr/athena-docs-sphinx/pull/12

**Comment by ctrlaltdavid** [comment]
Merged and Web site updated.
